name: Check for new gevent release

on:
  schedule:
    - cron: '0 0 * * MON'
  workflow_dispatch:

jobs:
  check-release:
    runs-on: ubuntu-20.04
    
    outputs:
      latest-release: ${{ steps.latest.outputs.LATEST_RELEASE }}
      current-release: ${{ steps.current.outputs.CURRENT_RELEASE }}

    steps:
      - uses: actions/checkout@v2

      - name: Get latest gevent release
        id: latest
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl jq
          
          GE_LATEST=$(curl -s https://pypi.org/pypi/gevent/json | jq -r '.info.version')
          echo '::set-output name=LATEST_RELEASE::'$GE_LATEST
          echo "Latest gevent version: "$GE_LATEST
          
      - name: Get current gevent release for Power
        id: current
        run: |
          GE_CURRENT=$(curl -s https://api.github.com/repos/IBM/oss-ecosystem-gevent/releases/latest | grep tag_name | cut -d '"' -f4)
          echo '::set-output name=CURRENT_RELEASE::'$GE_CURRENT
          echo "Current gevent version on Power: "$GE_CURRENT
          
  build-new-release:
    needs: [check-release]
    if: ${{ needs.check-release.outputs.latest-release }} != ${{ needs.check-release.outputs.current-release }}
    uses: ./.github/workflows/build_gevent.yaml
    with:
      release: 21.8.0
